### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by iyjian** [iyjian/wechatyTest#2]
```
(node:22391) UnhandledPromiseRejectionWarning: OpenError: IO error: lock /Users/wuchong/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_rhlfugm72vft12/room-member-raw-payload/LOCK: Resource temporarily unavailable
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_levelup@4.2.0@levelup/lib/levelup.js:96:23
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@6.1.1@abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_deferred-leveldown@5.2.0@deferred-leveldown/deferred-leveldown.js:21:21
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@6.1.1@abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@5.0.0@abstract-leveldown/abstract-leveldown.js:41:14
warning.js:18
(node:22391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
warning.js:18
(node:22391) UnhandledPromiseRejectionWarning: OpenError: IO error: lock /Users/wuchong/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_rhlfugm72vft12/room-raw-payload/LOCK: Resource temporarily unavailable
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_levelup@4.2.0@levelup/lib/levelup.js:96:23
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@6.1.1@abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_deferred-leveldown@5.2.0@deferred-leveldown/deferred-leveldown.js:21:21
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@6.1.1@abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@5.0.0@abstract-leveldown/abstract-leveldown.js:41:14
warning.js:18
(node:22391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
warning.js:18
(node:22391) UnhandledPromiseRejectionWarning: OpenError: IO error: lock /Users/wuchong/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_rhlfugm72vft12/friendship/LOCK: Resource temporarily unavailable
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_levelup@4.2.0@levelup/lib/levelup.js:96:23
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@6.1.1@abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_deferred-leveldown@5.2.0@deferred-leveldown/deferred-leveldown.js:21:21
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@6.1.1@abstract-leveldown/abstract-leveldown.js:30:14
    at /Users/wuchong/projects/bolome/wechatyTest/node_modules/_abstract-leveldown@5.0.0@abstract-leveldown/abstract-leveldown.js:41:14
warning.js:18
(node:22391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by iyjian** [comment]
```javascript

    const baseDir = path.join(
      os.homedir(),
      path.sep,
      '.wechaty',
      'puppet-padplus-cache',
      path.sep,
      'flash-store-v0.14',
      path.sep,
      'wxid_rhlfugm72vft12'
    )
const cacheContactRawPayload  = new FlashStore(path.join(baseDir, 'contact-raw-payload'))

const cacheContactRawPayload.set(1,'test')

```

**Comment by iyjian** [comment]
if you are sure there is no other process is accessing the database, you can simply delete the LOCK file.
